FROM php:8.2-fpm

ARG TIMEZONE
ARG USER_ID=1000
ARG GROUP_ID=1000

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    libzip-dev \
    zip \
    unzip\
    nodejs \
    npm \
    openssl \
    # Ajout pour wkhtmltopdf si nécessaire
    wkhtmltopdf

# Installation de Yarn via npm
RUN npm install -g yarn

# Install PHP extensions
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd zip intl opcache

# Set timezone
RUN ln -snf /usr/share/zoneinfo/${TIMEZONE} /etc/localtime && echo ${TIMEZONE} > /etc/timezone \
    && printf '[PHP]\ndate.timezone = "%s"\n', ${TIMEZONE} > /usr/local/etc/php/conf.d/tzone.ini

# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Configure PHP
COPY php.ini /usr/local/etc/php/conf.d/

# Create user with same permissions as host machine user
RUN usermod -u ${USER_ID} www-data && groupmod -g ${GROUP_ID} www-data

WORKDIR /var/www/

# Create directories and set proper permissions - VERSION CORRIGÉE
RUN mkdir -p /var/www/var/cache/prod/vich_uploader \
    && mkdir -p /var/www/var/cache/dev/vich_uploader \
    && mkdir -p /var/www/var/cache/prod/jms_metadata \
    && mkdir -p /var/www/var/cache/dev/jms_metadata \
    && mkdir -p /var/www/var/log \
    && mkdir -p /var/www/public/uploads/sessions \
    && mkdir -p /var/www/public/uploads/formations \
    && mkdir -p /var/www/config/jwt \
    # Permissions très permissives pour éviter les problèmes en production
    && chown -R www-data:www-data /var/www/var \
    && chown -R www-data:www-data /var/www/public \
    && chmod -R 777 /var/www/var/cache \
    && chmod -R 777 /var/www/var/log \
    && chmod -R 755 /var/www/public

# Copy entrypoint script from the correct path
COPY docker-entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

# Set entrypoint
ENTRYPOINT ["docker-entrypoint.sh"]
RUN echo "listen = 0.0.0.0:9000" >> /usr/local/etc/php-fpm.d/www.conf

# Keep container active
CMD ["php-fpm"]
