services:
  nginx:
    image: nginx:alpine
    container_name: merel_nginx
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php


  php:
    build:
      context: ./docker/php
      args:
        TIMEZONE: Europe/Paris
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    container_name: merel_php
    working_dir: /var/www
    volumes:
      - ./app:/var/www
    depends_on:
      - mysql


  mysql:
    image: mysql:8.0
    container_name: merel_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: merel_db
      MYSQL_USER: merel_user
      MYSQL_PASSWORD: merel_pass


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: merel_phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql


  mailhog:
    image: mailhog/mailhog
    container_name: merel_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  node:
    image: node:18
    container_name: merel_node
    working_dir: /var/www/assets
    volumes:
      - ./app:/var/www
    ports:
      - "5173:5173"
      - "4173:4173"
    command: /bin/sh -c "npm install && npm run dev -- --host"
    environment:
      - HOST=0.0.0.0
    stdin_open: true
    tty: true

