controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login_check:
    path: /api/login_check
    methods: ['POST']

gesdinet_jwt_refresh_token:
    path: /api/token/refresh
    methods: ['POST']