vich_uploader:
    db_driver: orm
    
    # Configuration corrigée pour la production
    metadata:
        type: attribute
        # Désactiver le cache de métadonnées pour éviter les erreurs de permissions en production
        cache: false
        # Optionnel: utiliser un cache alternatif si nécessaire
        # cache: array
        
    mappings:
        # Documents génériques (utilisé par l'entité Document)
        session_documents:
            uri_prefix: /uploads/documents
            upload_destination: '%kernel.project_dir%/public/uploads/documents'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            
        # Documents temporaires (système TempDocument)
        temp_documents:
            uri_prefix: /uploads/temp
            upload_destination: '%kernel.project_dir%/public/uploads/temp'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: false
            delete_on_remove: true
