vich_uploader:
    db_driver: orm
    mappings:
        session_documents:
            uri_prefix: /uploads/sessions
            upload_destination: '%kernel.project_dir%/public/uploads/sessions'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
